/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: { "surface-dim": "#dbdad6", "secondary": "#1f6c3a", "primary-fixed-dim": "#ffb4ac", "tertiary": "#572c00", "tertiary-fixed-dim": "#ffb77d", "surface-container-low": "#f5f3ef", "primary-fixed": "#ffdad6", "on-surface": "#1b1c1a", "on-error": "#ffffff", "surface-container": "#efeeea", "surface-tint": "#b02d29", "on-primary-fixed-variant": "#8e1214", "primary-container": "#991b1b", "on-primary-container": "#ffaaa1", "error-container": "#ffdad6", "on-secondary-fixed-variant": "#005226", "surface-variant": "#e4e2de", "inverse-surface": "#30312e", "outline": "#8d706d", "on-tertiary-fixed": "#2f1500", "on-tertiary": "#ffffff", "on-error-container": "#93000a", "on-secondary": "#ffffff", "on-tertiary-container": "#ffae6a", "on-secondary-fixed": "#00210b", "surface-bright": "#fbf9f5", "inverse-on-surface": "#f2f0ed", "background": "#fbf9f5", "surface-container-high": "#eae8e4", "on-background": "#1b1c1a", "tertiary-container": "#793f00", "on-primary-fixed": "#410002", "surface": "#fbf9f5", "outline-variant": "#e1bfbb", "secondary-container": "#a4f1b2", "tertiary-fixed": "#ffdcc3", "on-secondary-container": "#24703e", "error": "#ba1a1a", "on-tertiary-fixed-variant": "#6e3900", "surface-container-lowest": "#ffffff", "surface-container-highest": "#e4e2de", "on-primary": "#ffffff", "secondary-fixed-dim": "#8bd79b", "on-surface-variant": "#59413e", "primary": "#760009", "inverse-primary": "#ffb4ac", "secondary-fixed": "#a6f4b5" },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
      spacing: { "space-xl": "2.5rem", "space-2xl": "4rem", "space-xs": "0.25rem", "gutter-mobile": "1rem", "space-lg": "1.5rem", "margin-mobile": "1.25rem", "space-md": "1rem", "space-sm": "0.5rem", "margin": "2.5rem", "gutter": "1.5rem" },
      fontFamily: { "headline-md": ["Playfair Display", "serif"], "body-sm": ["Plus Jakarta Sans", "sans-serif"], "display-hero-mobile": ["Playfair Display", "serif"], "headline-sm": ["Playfair Display", "serif"], "label-md": ["Plus Jakarta Sans", "sans-serif"], "title-lg": ["Plus Jakarta Sans", "sans-serif"], "headline-lg-mobile": ["Playfair Display", "serif"], "label-sm": ["Plus Jakarta Sans", "sans-serif"], "display-hero": ["Playfair Display", "serif"], "label-lg": ["Plus Jakarta Sans", "sans-serif"], "body-lg": ["Plus Jakarta Sans", "sans-serif"], "body-md": ["Plus Jakarta Sans", "sans-serif"], "headline-lg": ["Playfair Display", "serif"] },
      fontSize: { "headline-md": ["26px", { "lineHeight": "34px", "fontWeight": "600" }], "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }], "display-hero-mobile": ["34px", { "lineHeight": "42px", "letterSpacing": "-0.01em", "fontWeight": "700" }], "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }], "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.03em", "fontWeight": "600" }], "title-lg": ["18px", { "lineHeight": "26px", "fontWeight": "700" }], "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "0em", "fontWeight": "700" }], "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "700" }], "display-hero": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "700" }], "label-lg": ["16px", { "lineHeight": "22px", "letterSpacing": "0.02em", "fontWeight": "700" }], "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }], "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }], "headline-lg": ["38px", { "lineHeight": "46px", "letterSpacing": "-0.01em", "fontWeight": "700" }] }
    }
  },
  plugins: [],
}
